### ISSUE TITLE
teste de bug

### ISSUE THREAD

**Issue by caiomcs04** [anacarolliny/JavaProjects#4]
Descrição do bug acompanhado de uma imagem

![Captura de tela de 2021-07-11 15-53-54](https://user-images.githubusercontent.com/66964367/125206967-3b073d00-e260-11eb-8418-af52b9c67a46.png)

**Comment by idavidd** [comment]
Quando irão resolver o bug? hahahaha

**Comment by caiomcs04** [comment]
está em andamento falta muuuuuito pouco kkkkkk

**Comment by anacarolliny** [comment]
> 
> 
> Quando irão resolver o bug? hahahaha

quando o @caiomcs04  me explicar melhor xD

**Comment by anacarolliny** [comment]
@caiomcs04 o bug seria que a linha 7 ta com espaço ?

![Capturar3](https://user-images.githubusercontent.com/80598323/125207318-0bf1cb00-e262-11eb-8f5e-6004cfc987c9.PNG)

**Comment by caiomcs04** [comment]
era só para demonstrar a aba Issues. por enquanto não ha bugs..... por enquanto rsrs

**Comment by caiomcs04** [comment]
fechando essa issue
